/** Design: Black Signal Theatre — a community field note combines one real event image with concise, verifiable open-source activity. */
import { ArrowUpRight, Github, Linkedin, UsersRound } from "lucide-react";
import { SectionSignal } from "@/components/SectionSignal";

const linkedinUrl = "https://www.linkedin.com/in/abdelrahman-mohamed-shehata-127a48366?utm_source=share_via&utm_content=profile&utm_medium=member_android";

export function CommunitySection() {
  return <section className="section community-section" id="community"><SectionSignal chapter="04" label="Community / Open source" />
    <div className="section-head reveal-up"><div><span className="eyebrow">Outside the repository</span><h2 className="section-title">Build in public.<br />Learn in the room.</h2></div><p className="section-lede">Technical growth is more useful when it connects to people, open collaboration, and practical conversations beyond a single project.</p></div>
    <div className="community-feature reveal-up"><figure className="community-image"><img alt="Google I/O Extended New Cairo attendees holding event tickets outside The Greek Campus" src="/manus-storage/google-io-new-cairo-community_c5c0776a.png" /><figcaption>Field note / Google I/O Extended New Cairo / 22 Aug 2026</figcaption></figure><article className="community-event"><span className="utility-label">Community event / 2026</span><h3>Google I/O<br />Extended<br /><em>New Cairo.</em></h3><p>Attended the Google Developer Groups event at The Greek Campus, Abdeen, engaging with the local developer community around Google AI, Android, and web platform updates.</p><div className="community-event-meta"><span>GDG New Cairo</span><span>Greek Campus, Abdeen</span><span>22 / 08 / 2026</span></div></article></div>
    <div className="community-ledger"><article className="community-metrics reveal-up"><span className="utility-label">Open-source signal</span><div><strong>15</strong><span>public repositories</span></div><div><strong>180+</strong><span>recorded commits</span></div><div><strong>5</strong><span>actively maintained projects</span></div></article><article className="community-copy reveal-up"><UsersRound aria-hidden="true" /><h3>Contributing to the tools and rooms that shape the work.</h3><p>Founder and lead developer of KING ABDO AI, contributor to Helwan Linux LTS, and an active learner in local developer events. The focus is sustained contribution: shipping useful tools, sharing work through public repositories, and learning alongside the community.</p><div className="community-links"><a href="https://github.com/A181-CODER" rel="noreferrer" target="_blank"><Github aria-hidden="true" /> GitHub <ArrowUpRight aria-hidden="true" /></a><a href={linkedinUrl} rel="noreferrer" target="_blank"><Linkedin aria-hidden="true" /> LinkedIn <ArrowUpRight aria-hidden="true" /></a></div></article></div>
  </section>;
}
